### ISSUE TITLE
There are some compatibility issues with the Join-vanish feature of essentialsx.

### ISSUE THREAD

**Issue by Huge-mistake** [alexdev03/UnlimitedNametags#14]
Plugin List：[packetevents-spigot-2.6.0，UnlimitedNametags1.6.4，LuckPerms，EssentialsX] (4)
server: paper-1.21.1-132

Situation Description: When an OP administrator has the 'essentials.silentjoin.vanish' permission and joins the server, UnlimitedNameTags cannot display the administrator's nametag.
Steps:
1. The server only has these 4 plugins installed. [packetevents，UnlimitedNametags，LuckPerms，EssentialsX]
2. LuckPerms grants the OP administrator the permission 'essentials.silentjoin.vanish
3. When an administrator joins the server, then leaves, and joins again, even if they use the command /vanish to disable their invisible status, UnlimitedNameTags will never display the administrator's nametag.
(**PS**:This issue only occurs with OP administrators; when non-administrators have the 'essentials.silentjoin.vanish' permission, this problem does not occur.)
At this point, the "essentials.silentjoin.vanish" permission must be revoked from the administrator and the server must be restarted for UnlimitedNameTags to properly display the OP administrator's nametag.

**Comment by alexdev03** [comment]
Hi, can you open a ticket with proof of purchase. Thanks
