### ISSUE TITLE
ViaVersion support

### ISSUE THREAD

**Issue by rudde0** [alexdev03/UnlimitedNametags#7]
Hello, a config option named `dont-handle-old-versions` would be nice since display entities isn't supported versions before 1.19.4. `dont-handle-old-versions` would keep normal behavior of nametags.

![image](https://github.com/user-attachments/assets/c4ff9cd4-2854-41ff-b336-b36df9908918)

**Comment by alexdev03** [comment]
Hi, sorry but my plugin is not intended to work with versions < 1.19.4

**Comment by rudde0** [comment]
I understand that its not working with <1.19.4 but my point is shouldn't break <1.19.4 clients. Older versions should see nametags just like in vanilla's behaviour, isn't it possible?

**Comment by Zarkness** [comment]
From what I was looking at, this plugin uses the new text display, instead of the armor stand as used in other versions
